"""
Create the soilgridsOCS artifact: soil organic carbon density (OCD) from SoilGrids 2.0,
at 6 standard depth layers, with low-resolution output generated by 1x1 degree
block-mean aggregation.

Usage:
    julia --project create_artifacts_interp.jl <path/to/soilgridsOCD_nc>

Steps before running this script:
    1. Run download_soilgrids_ocd.sh  (requires gdal_translate + gdalwarp)
    2. Run transform_geotiff_to_netcdf.sh
    3. Run this script with the path to the nc directory as argument
"""

using NCDatasets
using ClimaArtifactsHelper

if length(ARGS) < 1
    @error("Please provide the local path to the raw nc data directory (soilgridsOCD_nc).")
else
    filedir = ARGS[1]
end

outputdir        = "soilgridsOCS"
outputdir_lowres = "soilgridsOCS_lowres"
for dir in [outputdir, outputdir_lowres]
    if isdir(dir)
        @warn "$dir already exists. Content will end up in the artifact and may be overwritten."
        @warn "Abort this calculation, unless you know what you are doing."
    else
        mkdir(dir)
    end
end

include("utils.jl")
include("combine_and_transform_raw_data.jl")
# After including combine_and_transform_raw_data.jl the following are defined:
#   nlayers, level_names, attrib_ocd, transform_ocd, data, lat, lon, nlat, nlon, z

# Combine per-layer files into a single NetCDF
files = ["ocd_$(ln)_mean_5000.nc" for ln in level_names]
outfilepath_tmp = joinpath(outputdir, "ocd_soilgrids_combined.nc")
create_combined_data!(data, files, attrib_ocd, transform_ocd, outfilepath_tmp)

replace_nan_with_zero(x) = isnan(x) ? typeof(x)(0) : x

function degree_bin_groups(coord)
    bins = floor.(Int, coord)
    unique_bins = sort(unique(bins))
    groups = [findall(==(b), bins) for b in unique_bins]
    centers = Float32.(unique_bins .+ 0.5)
    return groups, centers
end

function aggregate_1deg_mean(data, lon, lat)
    lon_groups, lon_centers = degree_bin_groups(lon)
    lat_groups, lat_centers = degree_bin_groups(lat)
    nz = size(data, 3)
    lat_weights = Float32.(max.(cosd.(lat), 0))

    out = fill(Float32(NaN), length(lon_groups), length(lat_groups), nz)

    for k in 1:nz
        for i in eachindex(lon_groups)
            for j in eachindex(lat_groups)
                block = @view data[lon_groups[i], lat_groups[j], k]
                lat_idx = lat_groups[j]
                block_weights = @view lat_weights[lat_idx]
                weighted_sum = 0.0f0
                weight_sum = 0.0f0
                for ii in axes(block, 1)
                    for jj in axes(block, 2)
                        v = block[ii, jj]
                        w = block_weights[jj]
                        if !isnan(v)
                            weighted_sum += Float32(v) * w
                            weight_sum += w
                        end
                    end
                end
                if weight_sum > 0
                    out[i, j, k] = weighted_sum / weight_sum
                end
            end
        end
    end

    return out, lon_centers, lat_centers
end

# --- Full resolution output ---
ocd_ds = NCDataset(outfilepath_tmp)
ocd = ocd_ds["ocd"][:, :, :]
close(ocd_ds)

outfilepath = joinpath(outputdir, "soil_ocd_soilgrids.nc")
ds = NCDataset(outfilepath, "c")
defDim(ds, "lon", nlon)
defDim(ds, "lat", nlat)
defDim(ds, "z", nlayers)
la = defVar(ds, "lat", Float32, ("lat",))
lo = defVar(ds, "lon", Float32, ("lon",))
zv = defVar(ds, "z", Float32, ("z",))
la.attrib["units"] = "degrees_north"
la.attrib["standard_name"] = "latitude"
lo.attrib["standard_name"] = "longitude"
lo.attrib["units"] = "degrees_east"
zv.attrib["standard_name"] = "depth"
zv.attrib["units"] = "m"
la[:] = lat
lo[:] = lon
zv[:] = z
var = defVar(ds, "ocd", Float32, ("lon", "lat", "z"))
var.attrib["units"] = "kg/m^3"
var.attrib["longname"] = "Soil organic carbon density"
var[:, :, :] = replace_nan_with_zero.(ocd)
close(ds)

# --- Low resolution output (~1 degree) ---
# Aggregate all source values that fall into the same 1x1 degree lon/lat bin.
# Calculate a latitude-area-weighted mean using cos(lat), ignoring NaNs.
# The output lon/lat coordinates are the centers of the bins.
ocd_lowres, lon_lowres, lat_lowres = aggregate_1deg_mean(ocd, lon, lat)

outfilepath_lowres = joinpath(outputdir_lowres, "soil_ocd_soilgrids_lowres.nc")
ds = NCDataset(outfilepath_lowres, "c")
defDim(ds, "lon", length(lon_lowres))
defDim(ds, "lat", length(lat_lowres))
defDim(ds, "z", nlayers)
la = defVar(ds, "lat", Float32, ("lat",))
lo = defVar(ds, "lon", Float32, ("lon",))
zv = defVar(ds, "z", Float32, ("z",))
la.attrib["units"] = "degrees_north"
la.attrib["standard_name"] = "latitude"
lo.attrib["standard_name"] = "longitude"
lo.attrib["units"] = "degrees_east"
zv.attrib["standard_name"] = "depth"
zv.attrib["units"] = "m"
la[:] = lat_lowres
lo[:] = lon_lowres
zv[:] = z
var = defVar(ds, "ocd", Float32, ("lon", "lat", "z"))
var.attrib["units"] = "kg/m^3"
var.attrib["longname"] = "Soil organic carbon density"
var[:, :, :] = replace_nan_with_zero.(ocd_lowres)
close(ds)

create_artifact_guided(outputdir; artifact_name = basename(@__DIR__))
create_artifact_guided(outputdir_lowres; artifact_name = basename(@__DIR__) * "_lowres_interp", append = true)
