# ERA5 Instantaneous Model Levels Artifact
#
# The source data is generated using scripts from the WeatherQuest repository. See the README.md for more details.

using ClimaArtifactsHelper

# Path to the source data (generated by WeatherQuest preprocessing scripts above)
const SOURCE_DATA_PATH = "/net/sampo/data1/wxquest_data/initial_conditions/initial_conditions_amip/era5_init_processed_internal_20100101_0000.nc"

# Output artifact directory
const OUTPUT_DIR = "era5_inst_model_levels_artifact"

if isdir(OUTPUT_DIR)
    @warn "$OUTPUT_DIR already exists. Content will end up in the artifact and may be overwritten."
    @warn "Abort this calculation, unless you know what you are doing."
else
    mkdir(OUTPUT_DIR)
end

# Copy the preprocessed file to the artifact directory
if !isfile(SOURCE_DATA_PATH)
    error("Source data file not found at $SOURCE_DATA_PATH. Please run the WeatherQuest preprocessing scripts first.")
end

@info "Copying data file to artifact directory..."
dest_file = joinpath(OUTPUT_DIR, basename(SOURCE_DATA_PATH))
run(`cp $SOURCE_DATA_PATH $dest_file`)

@info "Data file copied!"
create_artifact_guided(OUTPUT_DIR; artifact_name = basename(@__DIR__))
