[ozone_concentrations_lowres]
git-tree-sha1 = "557c4120f3506c1bc399e9caab5a0031b0123f34"

    [[ozone_concentrations_lowres.download]]
    sha256 = "0ba5d9b66a92dcf6671ed6b8d4ad79ec44a72fafa70f785f4c98c03427a7bd09"
    url = "https://caltech.box.com/shared/static/6c16wt7i1htxq6tadpt1ng2uftjgdtpr.gz"
