[tripolar_one_degree_bathymetry]
git-tree-sha1 = "bc3ca2024cc0f2f918fd2685615a9382908fbbe4"

    [[tripolar_one_degree_bathymetry.download]]
    sha256 = "4ead74da0626f260ded7e2b9797af810d11e6cd774ca4bd25668f6a1f2059c89"
    url = "https://caltech.box.com/shared/static/1e4cvzlyqglursxsh8ca2km1v04eolvg.gz"
