[era5_lake_cover_and_depth]
git-tree-sha1 = "da338fdaf3704c744a90f79e1b84526afc9f092b"

    [[era5_lake_cover_and_depth.download]]
    sha256 = "d822dfccbe72d194c3e7bc5e88e6485c0496fdef4ee5b33aa6e1ce9dae746389"
    url = "https://caltech.box.com/shared/static/andadm1km9mitehanga1ae186u0drw2p.gz"
